### ISSUE TITLE
Telangana district JSON data

### ISSUE THREAD

**Issue by gpavanb-osi** [sansiddhjain/sansiddhjain.github.io#1]
Do you know if there is any resource where the current district data of Telangana is available? Your current website still hosts the older partition of districts.

**Comment by sansiddhjain** [comment]
I found this repo online -
https://github.com/gggodhwani/telangana_boundaries

Let me know if this works. Also may I know what you are using it for?

**Comment by gpavanb-osi** [comment]
Thanks for the prompt response. 
I have already posted a request in that repository.
We are using to create dashboards using D3.js for Telangana.
